### ISSUE TITLE
Time to update `0.3.0`

### ISSUE THREAD

**Issue by petamoriken** [aFarkas/requestIdleCallback#3]
The following commit from `0.2.0` has been made
- [non browser support](https://github.com/aFarkas/requestIdleCallback/commit/3fea1e04ec1c8bb79d5d12bdc29ff1fa4310b235)
- [use passive event](https://github.com/aFarkas/requestIdleCallback/commit/3fea1e04ec1c8bb79d5d12bdc29ff1fa4310b235) #2

Would you update the package.json version to `0.3.0` and execute `npm publish`?

**Comment by aFarkas** [comment]
done. Thanks for your help!
